// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebutviklingsEksamen.Contexts;

#nullable disable

namespace F1WebApi.Migrations
{
    [DbContext(typeof(F1Context))]
    [Migration("20231121221505_version19")]
    partial class version19
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("WebutviklingsEksamen.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "country");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "image");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "team");

                    b.HasKey("Id");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("WebutviklingsEksamen.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("GrandPrix")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "grandPrix");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "image");

                    b.Property<int>("Laps")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "laps");

                    b.Property<string>("Winner")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "winner");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("WebutviklingsEksamen.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Base")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "base");

                    b.Property<string>("FullTeamName")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "fullTeamName");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "image");

                    b.Property<string>("WorldChampionships")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "worldChampionships");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
